package main

// Code generated by peg grammer.peg DO NOT EDIT.

import (
	"fmt"
	"github.com/jiro4989/xlsxlang/token"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleprogram
	rulecell
	rulelist
	ruleatom
	rulebool
	ruleint
	rulestr
	rulenil
	rulesymbol
	rulespace
	ruleparen
	ruledelimiter
	rulecomment
	ruleeol
	ruleAction0
	ruleAction1
	rulePegText
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
)

var rul3s = [...]string{
	"Unknown",
	"program",
	"cell",
	"list",
	"atom",
	"bool",
	"int",
	"str",
	"nil",
	"symbol",
	"space",
	"paren",
	"delimiter",
	"comment",
	"eol",
	"Action0",
	"Action1",
	"PegText",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	token.Tokenizer

	Buffer string
	buffer []rune
	rules  [23]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *Parser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.Begin()
		case ruleAction1:
			p.End()
		case ruleAction2:
			p.PushBool(text)
		case ruleAction3:
			p.PushInt(text)
		case ruleAction4:
			p.PushStr(text)
		case ruleAction5:
			p.PushNil()
		case ruleAction6:
			p.PushSymbol(text)

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 program <- <cell+> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rulecell]() {
					goto l0
				}
			l2:
				{
					position3, tokenIndex3 := position, tokenIndex
					if !_rules[rulecell]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position3, tokenIndex3
				}
				add(ruleprogram, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 cell <- <(space* (comment / list / atom) space*)> */
		func() bool {
			position4, tokenIndex4 := position, tokenIndex
			{
				position5 := position
			l6:
				{
					position7, tokenIndex7 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l7
					}
					goto l6
				l7:
					position, tokenIndex = position7, tokenIndex7
				}
				{
					position8, tokenIndex8 := position, tokenIndex
					if !_rules[rulecomment]() {
						goto l9
					}
					goto l8
				l9:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[rulelist]() {
						goto l10
					}
					goto l8
				l10:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleatom]() {
						goto l4
					}
				}
			l8:
			l11:
				{
					position12, tokenIndex12 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l12
					}
					goto l11
				l12:
					position, tokenIndex = position12, tokenIndex12
				}
				add(rulecell, position5)
			}
			return true
		l4:
			position, tokenIndex = position4, tokenIndex4
			return false
		},
		/* 2 list <- <('(' Action0 cell+ ')' Action1)> */
		func() bool {
			position13, tokenIndex13 := position, tokenIndex
			{
				position14 := position
				if buffer[position] != rune('(') {
					goto l13
				}
				position++
				if !_rules[ruleAction0]() {
					goto l13
				}
				if !_rules[rulecell]() {
					goto l13
				}
			l15:
				{
					position16, tokenIndex16 := position, tokenIndex
					if !_rules[rulecell]() {
						goto l16
					}
					goto l15
				l16:
					position, tokenIndex = position16, tokenIndex16
				}
				if buffer[position] != rune(')') {
					goto l13
				}
				position++
				if !_rules[ruleAction1]() {
					goto l13
				}
				add(rulelist, position14)
			}
			return true
		l13:
			position, tokenIndex = position13, tokenIndex13
			return false
		},
		/* 3 atom <- <(bool / int / str / nil / symbol)> */
		func() bool {
			position17, tokenIndex17 := position, tokenIndex
			{
				position18 := position
				{
					position19, tokenIndex19 := position, tokenIndex
					if !_rules[rulebool]() {
						goto l20
					}
					goto l19
				l20:
					position, tokenIndex = position19, tokenIndex19
					if !_rules[ruleint]() {
						goto l21
					}
					goto l19
				l21:
					position, tokenIndex = position19, tokenIndex19
					if !_rules[rulestr]() {
						goto l22
					}
					goto l19
				l22:
					position, tokenIndex = position19, tokenIndex19
					if !_rules[rulenil]() {
						goto l23
					}
					goto l19
				l23:
					position, tokenIndex = position19, tokenIndex19
					if !_rules[rulesymbol]() {
						goto l17
					}
				}
			l19:
				add(ruleatom, position18)
			}
			return true
		l17:
			position, tokenIndex = position17, tokenIndex17
			return false
		},
		/* 4 bool <- <(<(('t' 'r' 'u' 'e') / ('f' 'a' 'l' 's' 'e'))> Action2)> */
		func() bool {
			position24, tokenIndex24 := position, tokenIndex
			{
				position25 := position
				{
					position26 := position
					{
						position27, tokenIndex27 := position, tokenIndex
						if buffer[position] != rune('t') {
							goto l28
						}
						position++
						if buffer[position] != rune('r') {
							goto l28
						}
						position++
						if buffer[position] != rune('u') {
							goto l28
						}
						position++
						if buffer[position] != rune('e') {
							goto l28
						}
						position++
						goto l27
					l28:
						position, tokenIndex = position27, tokenIndex27
						if buffer[position] != rune('f') {
							goto l24
						}
						position++
						if buffer[position] != rune('a') {
							goto l24
						}
						position++
						if buffer[position] != rune('l') {
							goto l24
						}
						position++
						if buffer[position] != rune('s') {
							goto l24
						}
						position++
						if buffer[position] != rune('e') {
							goto l24
						}
						position++
					}
				l27:
					add(rulePegText, position26)
				}
				if !_rules[ruleAction2]() {
					goto l24
				}
				add(rulebool, position25)
			}
			return true
		l24:
			position, tokenIndex = position24, tokenIndex24
			return false
		},
		/* 5 int <- <(<(([1-9] [0-9]*) / '0')> Action3)> */
		func() bool {
			position29, tokenIndex29 := position, tokenIndex
			{
				position30 := position
				{
					position31 := position
					{
						position32, tokenIndex32 := position, tokenIndex
						if c := buffer[position]; c < rune('1') || c > rune('9') {
							goto l33
						}
						position++
					l34:
						{
							position35, tokenIndex35 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l35
							}
							position++
							goto l34
						l35:
							position, tokenIndex = position35, tokenIndex35
						}
						goto l32
					l33:
						position, tokenIndex = position32, tokenIndex32
						if buffer[position] != rune('0') {
							goto l29
						}
						position++
					}
				l32:
					add(rulePegText, position31)
				}
				if !_rules[ruleAction3]() {
					goto l29
				}
				add(ruleint, position30)
			}
			return true
		l29:
			position, tokenIndex = position29, tokenIndex29
			return false
		},
		/* 6 str <- <('"' <((!('"' / '\\') .) / '\\')*> '"' Action4)> */
		func() bool {
			position36, tokenIndex36 := position, tokenIndex
			{
				position37 := position
				if buffer[position] != rune('"') {
					goto l36
				}
				position++
				{
					position38 := position
				l39:
					{
						position40, tokenIndex40 := position, tokenIndex
						{
							position41, tokenIndex41 := position, tokenIndex
							{
								position43, tokenIndex43 := position, tokenIndex
								{
									position44, tokenIndex44 := position, tokenIndex
									if buffer[position] != rune('"') {
										goto l45
									}
									position++
									goto l44
								l45:
									position, tokenIndex = position44, tokenIndex44
									if buffer[position] != rune('\\') {
										goto l43
									}
									position++
								}
							l44:
								goto l42
							l43:
								position, tokenIndex = position43, tokenIndex43
							}
							if !matchDot() {
								goto l42
							}
							goto l41
						l42:
							position, tokenIndex = position41, tokenIndex41
							if buffer[position] != rune('\\') {
								goto l40
							}
							position++
						}
					l41:
						goto l39
					l40:
						position, tokenIndex = position40, tokenIndex40
					}
					add(rulePegText, position38)
				}
				if buffer[position] != rune('"') {
					goto l36
				}
				position++
				if !_rules[ruleAction4]() {
					goto l36
				}
				add(rulestr, position37)
			}
			return true
		l36:
			position, tokenIndex = position36, tokenIndex36
			return false
		},
		/* 7 nil <- <('n' 'i' 'l' Action5)> */
		func() bool {
			position46, tokenIndex46 := position, tokenIndex
			{
				position47 := position
				if buffer[position] != rune('n') {
					goto l46
				}
				position++
				if buffer[position] != rune('i') {
					goto l46
				}
				position++
				if buffer[position] != rune('l') {
					goto l46
				}
				position++
				if !_rules[ruleAction5]() {
					goto l46
				}
				add(rulenil, position47)
			}
			return true
		l46:
			position, tokenIndex = position46, tokenIndex46
			return false
		},
		/* 8 symbol <- <(<(!delimiter .)+> Action6)> */
		func() bool {
			position48, tokenIndex48 := position, tokenIndex
			{
				position49 := position
				{
					position50 := position
					{
						position53, tokenIndex53 := position, tokenIndex
						if !_rules[ruledelimiter]() {
							goto l53
						}
						goto l48
					l53:
						position, tokenIndex = position53, tokenIndex53
					}
					if !matchDot() {
						goto l48
					}
				l51:
					{
						position52, tokenIndex52 := position, tokenIndex
						{
							position54, tokenIndex54 := position, tokenIndex
							if !_rules[ruledelimiter]() {
								goto l54
							}
							goto l52
						l54:
							position, tokenIndex = position54, tokenIndex54
						}
						if !matchDot() {
							goto l52
						}
						goto l51
					l52:
						position, tokenIndex = position52, tokenIndex52
					}
					add(rulePegText, position50)
				}
				if !_rules[ruleAction6]() {
					goto l48
				}
				add(rulesymbol, position49)
			}
			return true
		l48:
			position, tokenIndex = position48, tokenIndex48
			return false
		},
		/* 9 space <- <(' ' / eol)> */
		func() bool {
			position55, tokenIndex55 := position, tokenIndex
			{
				position56 := position
				{
					position57, tokenIndex57 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l58
					}
					position++
					goto l57
				l58:
					position, tokenIndex = position57, tokenIndex57
					if !_rules[ruleeol]() {
						goto l55
					}
				}
			l57:
				add(rulespace, position56)
			}
			return true
		l55:
			position, tokenIndex = position55, tokenIndex55
			return false
		},
		/* 10 paren <- <('(' / ')')> */
		func() bool {
			position59, tokenIndex59 := position, tokenIndex
			{
				position60 := position
				{
					position61, tokenIndex61 := position, tokenIndex
					if buffer[position] != rune('(') {
						goto l62
					}
					position++
					goto l61
				l62:
					position, tokenIndex = position61, tokenIndex61
					if buffer[position] != rune(')') {
						goto l59
					}
					position++
				}
			l61:
				add(ruleparen, position60)
			}
			return true
		l59:
			position, tokenIndex = position59, tokenIndex59
			return false
		},
		/* 11 delimiter <- <(paren / space)> */
		func() bool {
			position63, tokenIndex63 := position, tokenIndex
			{
				position64 := position
				{
					position65, tokenIndex65 := position, tokenIndex
					if !_rules[ruleparen]() {
						goto l66
					}
					goto l65
				l66:
					position, tokenIndex = position65, tokenIndex65
					if !_rules[rulespace]() {
						goto l63
					}
				}
			l65:
				add(ruledelimiter, position64)
			}
			return true
		l63:
			position, tokenIndex = position63, tokenIndex63
			return false
		},
		/* 12 comment <- <(space* ';' (!eol .)*)> */
		func() bool {
			position67, tokenIndex67 := position, tokenIndex
			{
				position68 := position
			l69:
				{
					position70, tokenIndex70 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l70
					}
					goto l69
				l70:
					position, tokenIndex = position70, tokenIndex70
				}
				if buffer[position] != rune(';') {
					goto l67
				}
				position++
			l71:
				{
					position72, tokenIndex72 := position, tokenIndex
					{
						position73, tokenIndex73 := position, tokenIndex
						if !_rules[ruleeol]() {
							goto l73
						}
						goto l72
					l73:
						position, tokenIndex = position73, tokenIndex73
					}
					if !matchDot() {
						goto l72
					}
					goto l71
				l72:
					position, tokenIndex = position72, tokenIndex72
				}
				add(rulecomment, position68)
			}
			return true
		l67:
			position, tokenIndex = position67, tokenIndex67
			return false
		},
		/* 13 eol <- <'\n'> */
		func() bool {
			position74, tokenIndex74 := position, tokenIndex
			{
				position75 := position
				if buffer[position] != rune('\n') {
					goto l74
				}
				position++
				add(ruleeol, position75)
			}
			return true
		l74:
			position, tokenIndex = position74, tokenIndex74
			return false
		},
		/* 15 Action0 <- <{ p.Begin() }> */
		func() bool {
			{
				add(ruleAction0, position)
			}
			return true
		},
		/* 16 Action1 <- <{ p.End() }> */
		func() bool {
			{
				add(ruleAction1, position)
			}
			return true
		},
		nil,
		/* 18 Action2 <- <{ p.PushBool(text) }> */
		func() bool {
			{
				add(ruleAction2, position)
			}
			return true
		},
		/* 19 Action3 <- <{ p.PushInt(text) }> */
		func() bool {
			{
				add(ruleAction3, position)
			}
			return true
		},
		/* 20 Action4 <- <{ p.PushStr(text) }> */
		func() bool {
			{
				add(ruleAction4, position)
			}
			return true
		},
		/* 21 Action5 <- <{ p.PushNil() }> */
		func() bool {
			{
				add(ruleAction5, position)
			}
			return true
		},
		/* 22 Action6 <- <{ p.PushSymbol(text) }> */
		func() bool {
			{
				add(ruleAction6, position)
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
