package main

// Code generated by peg grammer.peg DO NOT EDIT.

import (
	"fmt"
	"github.com/jiro4989/xlsxlang/token"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleprogram
	rulecell
	rulelist
	ruleatom
	rulebool
	ruleint
	rulestr
	rulenil
	rulesymbol
	rulespace
	ruleparen
	ruledelimiter
	rulecomment
	ruleeol
	ruleAction0
	ruleAction1
	rulePegText
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
)

var rul3s = [...]string{
	"Unknown",
	"program",
	"cell",
	"list",
	"atom",
	"bool",
	"int",
	"str",
	"nil",
	"symbol",
	"space",
	"paren",
	"delimiter",
	"comment",
	"eol",
	"Action0",
	"Action1",
	"PegText",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	token.Tokenizer

	Buffer string
	buffer []rune
	rules  [23]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *Parser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.Begin()
		case ruleAction1:
			p.End()
		case ruleAction2:
			p.PushBool(text)
		case ruleAction3:
			p.PushInt(text)
		case ruleAction4:
			p.PushStr(text)
		case ruleAction5:
			p.PushNil()
		case ruleAction6:
			p.PushSymbol(text)

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 program <- <(comment / cell)+> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position4, tokenIndex4 := position, tokenIndex
					if !_rules[rulecomment]() {
						goto l5
					}
					goto l4
				l5:
					position, tokenIndex = position4, tokenIndex4
					if !_rules[rulecell]() {
						goto l0
					}
				}
			l4:
			l2:
				{
					position3, tokenIndex3 := position, tokenIndex
					{
						position6, tokenIndex6 := position, tokenIndex
						if !_rules[rulecomment]() {
							goto l7
						}
						goto l6
					l7:
						position, tokenIndex = position6, tokenIndex6
						if !_rules[rulecell]() {
							goto l3
						}
					}
				l6:
					goto l2
				l3:
					position, tokenIndex = position3, tokenIndex3
				}
				add(ruleprogram, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 cell <- <(space* (list / atom) space*)> */
		func() bool {
			position8, tokenIndex8 := position, tokenIndex
			{
				position9 := position
			l10:
				{
					position11, tokenIndex11 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l11
					}
					goto l10
				l11:
					position, tokenIndex = position11, tokenIndex11
				}
				{
					position12, tokenIndex12 := position, tokenIndex
					if !_rules[rulelist]() {
						goto l13
					}
					goto l12
				l13:
					position, tokenIndex = position12, tokenIndex12
					if !_rules[ruleatom]() {
						goto l8
					}
				}
			l12:
			l14:
				{
					position15, tokenIndex15 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l15
					}
					goto l14
				l15:
					position, tokenIndex = position15, tokenIndex15
				}
				add(rulecell, position9)
			}
			return true
		l8:
			position, tokenIndex = position8, tokenIndex8
			return false
		},
		/* 2 list <- <('(' Action0 cell+ ')' Action1)> */
		func() bool {
			position16, tokenIndex16 := position, tokenIndex
			{
				position17 := position
				if buffer[position] != rune('(') {
					goto l16
				}
				position++
				if !_rules[ruleAction0]() {
					goto l16
				}
				if !_rules[rulecell]() {
					goto l16
				}
			l18:
				{
					position19, tokenIndex19 := position, tokenIndex
					if !_rules[rulecell]() {
						goto l19
					}
					goto l18
				l19:
					position, tokenIndex = position19, tokenIndex19
				}
				if buffer[position] != rune(')') {
					goto l16
				}
				position++
				if !_rules[ruleAction1]() {
					goto l16
				}
				add(rulelist, position17)
			}
			return true
		l16:
			position, tokenIndex = position16, tokenIndex16
			return false
		},
		/* 3 atom <- <(bool / int / str / nil / symbol)> */
		func() bool {
			position20, tokenIndex20 := position, tokenIndex
			{
				position21 := position
				{
					position22, tokenIndex22 := position, tokenIndex
					if !_rules[rulebool]() {
						goto l23
					}
					goto l22
				l23:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleint]() {
						goto l24
					}
					goto l22
				l24:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[rulestr]() {
						goto l25
					}
					goto l22
				l25:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[rulenil]() {
						goto l26
					}
					goto l22
				l26:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[rulesymbol]() {
						goto l20
					}
				}
			l22:
				add(ruleatom, position21)
			}
			return true
		l20:
			position, tokenIndex = position20, tokenIndex20
			return false
		},
		/* 4 bool <- <(<(('t' 'r' 'u' 'e') / ('f' 'a' 'l' 's' 'e'))> Action2)> */
		func() bool {
			position27, tokenIndex27 := position, tokenIndex
			{
				position28 := position
				{
					position29 := position
					{
						position30, tokenIndex30 := position, tokenIndex
						if buffer[position] != rune('t') {
							goto l31
						}
						position++
						if buffer[position] != rune('r') {
							goto l31
						}
						position++
						if buffer[position] != rune('u') {
							goto l31
						}
						position++
						if buffer[position] != rune('e') {
							goto l31
						}
						position++
						goto l30
					l31:
						position, tokenIndex = position30, tokenIndex30
						if buffer[position] != rune('f') {
							goto l27
						}
						position++
						if buffer[position] != rune('a') {
							goto l27
						}
						position++
						if buffer[position] != rune('l') {
							goto l27
						}
						position++
						if buffer[position] != rune('s') {
							goto l27
						}
						position++
						if buffer[position] != rune('e') {
							goto l27
						}
						position++
					}
				l30:
					add(rulePegText, position29)
				}
				if !_rules[ruleAction2]() {
					goto l27
				}
				add(rulebool, position28)
			}
			return true
		l27:
			position, tokenIndex = position27, tokenIndex27
			return false
		},
		/* 5 int <- <(<(([1-9] [0-9]*) / '0')> Action3)> */
		func() bool {
			position32, tokenIndex32 := position, tokenIndex
			{
				position33 := position
				{
					position34 := position
					{
						position35, tokenIndex35 := position, tokenIndex
						if c := buffer[position]; c < rune('1') || c > rune('9') {
							goto l36
						}
						position++
					l37:
						{
							position38, tokenIndex38 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l38
							}
							position++
							goto l37
						l38:
							position, tokenIndex = position38, tokenIndex38
						}
						goto l35
					l36:
						position, tokenIndex = position35, tokenIndex35
						if buffer[position] != rune('0') {
							goto l32
						}
						position++
					}
				l35:
					add(rulePegText, position34)
				}
				if !_rules[ruleAction3]() {
					goto l32
				}
				add(ruleint, position33)
			}
			return true
		l32:
			position, tokenIndex = position32, tokenIndex32
			return false
		},
		/* 6 str <- <('"' <((!('"' / '\\') .) / '\\')*> '"' Action4)> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				if buffer[position] != rune('"') {
					goto l39
				}
				position++
				{
					position41 := position
				l42:
					{
						position43, tokenIndex43 := position, tokenIndex
						{
							position44, tokenIndex44 := position, tokenIndex
							{
								position46, tokenIndex46 := position, tokenIndex
								{
									position47, tokenIndex47 := position, tokenIndex
									if buffer[position] != rune('"') {
										goto l48
									}
									position++
									goto l47
								l48:
									position, tokenIndex = position47, tokenIndex47
									if buffer[position] != rune('\\') {
										goto l46
									}
									position++
								}
							l47:
								goto l45
							l46:
								position, tokenIndex = position46, tokenIndex46
							}
							if !matchDot() {
								goto l45
							}
							goto l44
						l45:
							position, tokenIndex = position44, tokenIndex44
							if buffer[position] != rune('\\') {
								goto l43
							}
							position++
						}
					l44:
						goto l42
					l43:
						position, tokenIndex = position43, tokenIndex43
					}
					add(rulePegText, position41)
				}
				if buffer[position] != rune('"') {
					goto l39
				}
				position++
				if !_rules[ruleAction4]() {
					goto l39
				}
				add(rulestr, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 7 nil <- <('n' 'i' 'l' Action5)> */
		func() bool {
			position49, tokenIndex49 := position, tokenIndex
			{
				position50 := position
				if buffer[position] != rune('n') {
					goto l49
				}
				position++
				if buffer[position] != rune('i') {
					goto l49
				}
				position++
				if buffer[position] != rune('l') {
					goto l49
				}
				position++
				if !_rules[ruleAction5]() {
					goto l49
				}
				add(rulenil, position50)
			}
			return true
		l49:
			position, tokenIndex = position49, tokenIndex49
			return false
		},
		/* 8 symbol <- <(<(!delimiter .)+> Action6)> */
		func() bool {
			position51, tokenIndex51 := position, tokenIndex
			{
				position52 := position
				{
					position53 := position
					{
						position56, tokenIndex56 := position, tokenIndex
						if !_rules[ruledelimiter]() {
							goto l56
						}
						goto l51
					l56:
						position, tokenIndex = position56, tokenIndex56
					}
					if !matchDot() {
						goto l51
					}
				l54:
					{
						position55, tokenIndex55 := position, tokenIndex
						{
							position57, tokenIndex57 := position, tokenIndex
							if !_rules[ruledelimiter]() {
								goto l57
							}
							goto l55
						l57:
							position, tokenIndex = position57, tokenIndex57
						}
						if !matchDot() {
							goto l55
						}
						goto l54
					l55:
						position, tokenIndex = position55, tokenIndex55
					}
					add(rulePegText, position53)
				}
				if !_rules[ruleAction6]() {
					goto l51
				}
				add(rulesymbol, position52)
			}
			return true
		l51:
			position, tokenIndex = position51, tokenIndex51
			return false
		},
		/* 9 space <- <(' ' / eol)> */
		func() bool {
			position58, tokenIndex58 := position, tokenIndex
			{
				position59 := position
				{
					position60, tokenIndex60 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l61
					}
					position++
					goto l60
				l61:
					position, tokenIndex = position60, tokenIndex60
					if !_rules[ruleeol]() {
						goto l58
					}
				}
			l60:
				add(rulespace, position59)
			}
			return true
		l58:
			position, tokenIndex = position58, tokenIndex58
			return false
		},
		/* 10 paren <- <('(' / ')')> */
		func() bool {
			position62, tokenIndex62 := position, tokenIndex
			{
				position63 := position
				{
					position64, tokenIndex64 := position, tokenIndex
					if buffer[position] != rune('(') {
						goto l65
					}
					position++
					goto l64
				l65:
					position, tokenIndex = position64, tokenIndex64
					if buffer[position] != rune(')') {
						goto l62
					}
					position++
				}
			l64:
				add(ruleparen, position63)
			}
			return true
		l62:
			position, tokenIndex = position62, tokenIndex62
			return false
		},
		/* 11 delimiter <- <(paren / space)> */
		func() bool {
			position66, tokenIndex66 := position, tokenIndex
			{
				position67 := position
				{
					position68, tokenIndex68 := position, tokenIndex
					if !_rules[ruleparen]() {
						goto l69
					}
					goto l68
				l69:
					position, tokenIndex = position68, tokenIndex68
					if !_rules[rulespace]() {
						goto l66
					}
				}
			l68:
				add(ruledelimiter, position67)
			}
			return true
		l66:
			position, tokenIndex = position66, tokenIndex66
			return false
		},
		/* 12 comment <- <(space* ';' (!eol .)*)> */
		func() bool {
			position70, tokenIndex70 := position, tokenIndex
			{
				position71 := position
			l72:
				{
					position73, tokenIndex73 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l73
					}
					goto l72
				l73:
					position, tokenIndex = position73, tokenIndex73
				}
				if buffer[position] != rune(';') {
					goto l70
				}
				position++
			l74:
				{
					position75, tokenIndex75 := position, tokenIndex
					{
						position76, tokenIndex76 := position, tokenIndex
						if !_rules[ruleeol]() {
							goto l76
						}
						goto l75
					l76:
						position, tokenIndex = position76, tokenIndex76
					}
					if !matchDot() {
						goto l75
					}
					goto l74
				l75:
					position, tokenIndex = position75, tokenIndex75
				}
				add(rulecomment, position71)
			}
			return true
		l70:
			position, tokenIndex = position70, tokenIndex70
			return false
		},
		/* 13 eol <- <'\n'> */
		func() bool {
			position77, tokenIndex77 := position, tokenIndex
			{
				position78 := position
				if buffer[position] != rune('\n') {
					goto l77
				}
				position++
				add(ruleeol, position78)
			}
			return true
		l77:
			position, tokenIndex = position77, tokenIndex77
			return false
		},
		/* 15 Action0 <- <{ p.Begin() }> */
		func() bool {
			{
				add(ruleAction0, position)
			}
			return true
		},
		/* 16 Action1 <- <{ p.End() }> */
		func() bool {
			{
				add(ruleAction1, position)
			}
			return true
		},
		nil,
		/* 18 Action2 <- <{ p.PushBool(text) }> */
		func() bool {
			{
				add(ruleAction2, position)
			}
			return true
		},
		/* 19 Action3 <- <{ p.PushInt(text) }> */
		func() bool {
			{
				add(ruleAction3, position)
			}
			return true
		},
		/* 20 Action4 <- <{ p.PushStr(text) }> */
		func() bool {
			{
				add(ruleAction4, position)
			}
			return true
		},
		/* 21 Action5 <- <{ p.PushNil() }> */
		func() bool {
			{
				add(ruleAction5, position)
			}
			return true
		},
		/* 22 Action6 <- <{ p.PushSymbol(text) }> */
		func() bool {
			{
				add(ruleAction6, position)
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
