package main

// Code generated by peg grammer.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleroot
	ruleexpression
	ruleadditive
	rulemultitive
	ruleprimary
	rulebool
	ruleNUMBER
	ruleTRUE
	ruleFALSE
	rule_
	ruleWHITESPACE
	ruleEOL
	ruleEOF
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	rulePegText
	ruleAction4
	ruleAction5
)

var rul3s = [...]string{
	"Unknown",
	"root",
	"expression",
	"additive",
	"multitive",
	"primary",
	"bool",
	"NUMBER",
	"TRUE",
	"FALSE",
	"_",
	"WHITESPACE",
	"EOL",
	"EOF",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"PegText",
	"Action4",
	"Action5",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	Calc

	Buffer string
	buffer []rune
	rules  [21]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *Parser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.PushOpe("+")
		case ruleAction1:
			p.PushOpe("-")
		case ruleAction2:
			p.PushOpe("*")
		case ruleAction3:
			p.PushOpe("/")
		case ruleAction4:
			p.PushDigit(text)
		case ruleAction5:
			p.PushBool(text)

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 root <- <expression> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleexpression]() {
					goto l0
				}
				add(ruleroot, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 expression <- <additive> */
		func() bool {
			position2, tokenIndex2 := position, tokenIndex
			{
				position3 := position
				if !_rules[ruleadditive]() {
					goto l2
				}
				add(ruleexpression, position3)
			}
			return true
		l2:
			position, tokenIndex = position2, tokenIndex2
			return false
		},
		/* 2 additive <- <(multitive ((_ '+' _ multitive Action0) / (_ '-' _ multitive Action1))*)> */
		func() bool {
			position4, tokenIndex4 := position, tokenIndex
			{
				position5 := position
				if !_rules[rulemultitive]() {
					goto l4
				}
			l6:
				{
					position7, tokenIndex7 := position, tokenIndex
					{
						position8, tokenIndex8 := position, tokenIndex
						if !_rules[rule_]() {
							goto l9
						}
						if buffer[position] != rune('+') {
							goto l9
						}
						position++
						if !_rules[rule_]() {
							goto l9
						}
						if !_rules[rulemultitive]() {
							goto l9
						}
						if !_rules[ruleAction0]() {
							goto l9
						}
						goto l8
					l9:
						position, tokenIndex = position8, tokenIndex8
						if !_rules[rule_]() {
							goto l7
						}
						if buffer[position] != rune('-') {
							goto l7
						}
						position++
						if !_rules[rule_]() {
							goto l7
						}
						if !_rules[rulemultitive]() {
							goto l7
						}
						if !_rules[ruleAction1]() {
							goto l7
						}
					}
				l8:
					goto l6
				l7:
					position, tokenIndex = position7, tokenIndex7
				}
				add(ruleadditive, position5)
			}
			return true
		l4:
			position, tokenIndex = position4, tokenIndex4
			return false
		},
		/* 3 multitive <- <(primary ((_ '*' _ primary Action2) / (_ '/' _ primary Action3))*)> */
		func() bool {
			position10, tokenIndex10 := position, tokenIndex
			{
				position11 := position
				if !_rules[ruleprimary]() {
					goto l10
				}
			l12:
				{
					position13, tokenIndex13 := position, tokenIndex
					{
						position14, tokenIndex14 := position, tokenIndex
						if !_rules[rule_]() {
							goto l15
						}
						if buffer[position] != rune('*') {
							goto l15
						}
						position++
						if !_rules[rule_]() {
							goto l15
						}
						if !_rules[ruleprimary]() {
							goto l15
						}
						if !_rules[ruleAction2]() {
							goto l15
						}
						goto l14
					l15:
						position, tokenIndex = position14, tokenIndex14
						if !_rules[rule_]() {
							goto l13
						}
						if buffer[position] != rune('/') {
							goto l13
						}
						position++
						if !_rules[rule_]() {
							goto l13
						}
						if !_rules[ruleprimary]() {
							goto l13
						}
						if !_rules[ruleAction3]() {
							goto l13
						}
					}
				l14:
					goto l12
				l13:
					position, tokenIndex = position13, tokenIndex13
				}
				add(rulemultitive, position11)
			}
			return true
		l10:
			position, tokenIndex = position10, tokenIndex10
			return false
		},
		/* 4 primary <- <(('(' _ expression _ ')') / (<NUMBER> Action4))> */
		func() bool {
			position16, tokenIndex16 := position, tokenIndex
			{
				position17 := position
				{
					position18, tokenIndex18 := position, tokenIndex
					if buffer[position] != rune('(') {
						goto l19
					}
					position++
					if !_rules[rule_]() {
						goto l19
					}
					if !_rules[ruleexpression]() {
						goto l19
					}
					if !_rules[rule_]() {
						goto l19
					}
					if buffer[position] != rune(')') {
						goto l19
					}
					position++
					goto l18
				l19:
					position, tokenIndex = position18, tokenIndex18
					{
						position20 := position
						if !_rules[ruleNUMBER]() {
							goto l16
						}
						add(rulePegText, position20)
					}
					if !_rules[ruleAction4]() {
						goto l16
					}
				}
			l18:
				add(ruleprimary, position17)
			}
			return true
		l16:
			position, tokenIndex = position16, tokenIndex16
			return false
		},
		/* 5 bool <- <((TRUE / FALSE) Action5)> */
		nil,
		/* 6 NUMBER <- <[0-9]+> */
		func() bool {
			position22, tokenIndex22 := position, tokenIndex
			{
				position23 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l22
				}
				position++
			l24:
				{
					position25, tokenIndex25 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l25
					}
					position++
					goto l24
				l25:
					position, tokenIndex = position25, tokenIndex25
				}
				add(ruleNUMBER, position23)
			}
			return true
		l22:
			position, tokenIndex = position22, tokenIndex22
			return false
		},
		/* 7 TRUE <- <('t' 'r' 'u' 'e')> */
		nil,
		/* 8 FALSE <- <('f' 'a' 'l' 's' 'e')> */
		nil,
		/* 9 _ <- <WHITESPACE*> */
		func() bool {
			{
				position29 := position
			l30:
				{
					position31, tokenIndex31 := position, tokenIndex
					if !_rules[ruleWHITESPACE]() {
						goto l31
					}
					goto l30
				l31:
					position, tokenIndex = position31, tokenIndex31
				}
				add(rule_, position29)
			}
			return true
		},
		/* 10 WHITESPACE <- <(' ' / '\n')> */
		func() bool {
			position32, tokenIndex32 := position, tokenIndex
			{
				position33 := position
				{
					position34, tokenIndex34 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l35
					}
					position++
					goto l34
				l35:
					position, tokenIndex = position34, tokenIndex34
					if buffer[position] != rune('\n') {
						goto l32
					}
					position++
				}
			l34:
				add(ruleWHITESPACE, position33)
			}
			return true
		l32:
			position, tokenIndex = position32, tokenIndex32
			return false
		},
		/* 11 EOL <- <'\n'> */
		nil,
		/* 12 EOF <- <!.> */
		nil,
		/* 14 Action0 <- <{p.PushOpe("+")}> */
		func() bool {
			{
				add(ruleAction0, position)
			}
			return true
		},
		/* 15 Action1 <- <{p.PushOpe("-")}> */
		func() bool {
			{
				add(ruleAction1, position)
			}
			return true
		},
		/* 16 Action2 <- <{p.PushOpe("*")}> */
		func() bool {
			{
				add(ruleAction2, position)
			}
			return true
		},
		/* 17 Action3 <- <{p.PushOpe("/")}> */
		func() bool {
			{
				add(ruleAction3, position)
			}
			return true
		},
		nil,
		/* 19 Action4 <- <{p.PushDigit(text)}> */
		func() bool {
			{
				add(ruleAction4, position)
			}
			return true
		},
		/* 20 Action5 <- <{p.PushBool(text)}> */
		nil,
	}
	p.rules = _rules
	return nil
}
